####################################
# 创建者：v2rayse.com
# 客户端：Clash
# 创建时间：2024-04-10 08:49:02
# 使用模版：NOAD
# 节点数量：6
# 节点类型：trojan, vmess
####################################
mixed-port: 7890
allow-lan: true
log-level: info
external-controller: 0.0.0.0:9090
dns:
  enabled: true
  listen: 0.0.0.0:1053
  ipv6: true
  default-nameserver:
    - 223.5.5.5
    - 114.114.114.114
  enhanced-mode: fake-ip
  fake-ip-range: 198.18.0.1/16
  fake-ip-filter:
    - '*.lan'
    - '*.linksys.com'
    - '*.linksyssmartwifi.com'
    - swscan.apple.com
    - mesu.apple.com
    - '*.msftconnecttest.com'
    - '*.msftncsi.com'
    - time.*.com
    - time.*.gov
    - time.*.edu.cn
    - time.*.apple.com
    - time1.*.com
    - time2.*.com
    - time3.*.com
    - time4.*.com
    - time5.*.com
    - time6.*.com
    - time7.*.com
    - ntp.*.com
    - ntp.*.com
    - ntp1.*.com
    - ntp2.*.com
    - ntp3.*.com
    - ntp4.*.com
    - ntp5.*.com
    - ntp6.*.com
    - ntp7.*.com
    - '*.time.edu.cn'
    - '*.ntp.org.cn'
    - +.pool.ntp.org
    - time1.cloud.tencent.com
    - +.music.163.com
    - '*.126.net'
    - musicapi.taihe.com
    - music.taihe.com
    - songsearch.kugou.com
    - trackercdn.kugou.com
    - '*.kuwo.cn'
    - api-jooxtt.sanook.com
    - api.joox.com
    - joox.com
    - +.y.qq.com
    - +.music.tc.qq.com
    - aqqmusic.tc.qq.com
    - +.stream.qqmusic.qq.com
    - '*.xiami.com'
    - +.music.migu.cn
    - +.srv.nintendo.net
    - +.stun.playstation.net
    - xbox.*.microsoft.com
    - +.xboxlive.com
    - localhost.ptlogin2.qq.com
    - proxy.golang.org
    - stun.*.*
    - stun.*.*.*
    - '*.mcdn.bilivideo.cn'
  nameserver:
    - https://doh.pub/dns-query
    - https://dns.alidns.com/dns-query
  fallback-filter:
    geoip: false
    ipcidr:
      - 240.0.0.0/4
      - 0.0.0.0/32

proxies:
  - {"name":"HK 01","type":"trojan","server":"cmsswfw.yushen.buzz","port":39646,"udp":true,"password":"a7cbb17e-f37b-d900-7e49-e02e2428354f","sni":"phk1.spacebooster.co","skip-cert-verify":true,"network":"tcp"}
  - {"name":"HK 02","type":"vmess","server":"183.240.179.195","port":15610,"cipher":"auto","uuid":"aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaad","alterId":0,"tls":false,"skip-cert-verify":true,"network":""}
  - {"name":"JP 01","type":"trojan","server":"tjlt.yushen.buzz","port":10450,"udp":true,"password":"1be9d575-058d-d73d-b5ef-28280638ddd6","sni":"polo.jp2.spacebooster.co","skip-cert-verify":true,"network":"tcp"}
  - {"name":"SG 01","type":"trojan","server":"tjlt.yushen.buzz","port":23556,"udp":true,"password":"b2ed99f0-a721-212c-ba7a-3edb7691c889","sni":"polo.sg2.spacebooster.co","skip-cert-verify":true,"network":"tcp"}
  - {"name":"KR 01 直连","type":"vmess","server":"125.129.194.28","port":48215,"cipher":"auto","uuid":"06d29f39-ff61-4592-8800-1e243045a123","alterId":0,"tls":false,"skip-cert-verify":true,"network":""}
  - {"name":"KR 02 直连","type":"vmess","server":"59.6.237.245","port":48215,"cipher":"auto","uuid":"06d29f39-ff61-4592-8800-1e243045a123","alterId":0,"tls":false,"skip-cert-verify":true,"network":""}
proxy-groups:
  - name: 节点选择
    type: select
    proxies:
      - 自动选择
      - HK 01
      - HK 02
      - JP 01
      - SG 01
      - KR 01 直连
      - KR 02 直连
  - name: 自动选择
    type: url-test
    url: http://www.apple.com/library/test/success.html
    interval: 60
    tolerance: 0
    proxies:
      - HK 01
      - HK 02
      - JP 01
      - SG 01
      - KR 01 直连
      - KR 02 直连
  - name: OpenAI
    type: url-test
    url: http://www.apple.com/library/test/success.html
    interval: 60
    tolerance: 0
    proxies:
      - JP 01
      - SG 01
      - KR 01 直连
      - KR 02 直连
  - name: 直连
    type: select
    proxies:
      - DIRECT
  - name: 拦截
    type: select
    proxies:
      - REJECT

rules:
# NAME: OpenAI
# AUTHOR: blackmatrix7
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2024-03-31 02:13:21
# DOMAIN: 2
# DOMAIN-KEYWORD: 1
# DOMAIN-SUFFIX: 22
# IP-CIDR: 2
# TOTAL: 27
# NAME: Lan
  - DOMAIN,browser-intake-datadoghq.com,OpenAI
  - DOMAIN,static.cloudflareinsights.com,OpenAI
  - DOMAIN-SUFFIX,ai.com,OpenAI
  - DOMAIN-SUFFIX,algolia.net,OpenAI
  - DOMAIN-SUFFIX,api.statsig.com,OpenAI
  - DOMAIN-SUFFIX,auth0.com,OpenAI
  - DOMAIN-SUFFIX,chatgpt.com,OpenAI
  - DOMAIN-SUFFIX,chatgpt.livekit.cloud,OpenAI
  - DOMAIN-SUFFIX,client-api.arkoselabs.com,OpenAI
  - DOMAIN-SUFFIX,events.statsigapi.net,OpenAI
  - DOMAIN-SUFFIX,featuregates.org,OpenAI
  - DOMAIN-SUFFIX,host.livekit.cloud,OpenAI
  - DOMAIN-SUFFIX,identrust.com,OpenAI
  - DOMAIN-SUFFIX,intercom.io,OpenAI
  - DOMAIN-SUFFIX,intercomcdn.com,OpenAI
  - DOMAIN-SUFFIX,launchdarkly.com,OpenAI
  - DOMAIN-SUFFIX,oaistatic.com,OpenAI
  - DOMAIN-SUFFIX,oaiusercontent.com,OpenAI
  - DOMAIN-SUFFIX,observeit.net,OpenAI
  - DOMAIN-SUFFIX,poe.com,OpenAI
  - DOMAIN-SUFFIX,segment.io,OpenAI
  - DOMAIN-SUFFIX,sentry.io,OpenAI
  - DOMAIN-SUFFIX,stripe.com,OpenAI
  - DOMAIN-SUFFIX,turn.livekit.cloud,OpenAI
  - DOMAIN-KEYWORD,openai,OpenAI
  - IP-CIDR,24.199.123.28/32,OpenAI,no-resolve
  - IP-CIDR,64.23.132.171/32,OpenAI,no-resolve
# AUTHOR: blackmatrix7
# REPO: https://github.com/blackmatrix7/ios_rule_script
# UPDATED: 2024-02-25 16:03:04
# DOMAIN: 7
# DOMAIN-SUFFIX: 123
# IP-CIDR: 14
# IP-CIDR6: 4
# TOTAL: 148
  - DOMAIN,asusrouter.com,直连
  - DOMAIN,cp.cloudflare.com,直连
  - DOMAIN,detectportal.firefox.com,直连
  - DOMAIN,instant.arubanetworks.com,直连
  - DOMAIN,router.asus.com,直连
  - DOMAIN,setmeup.arubanetworks.com,直连
  - DOMAIN,www.asusrouter.com,直连
  - DOMAIN-SUFFIX,0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa,直连
  - DOMAIN-SUFFIX,0.in-addr.arpa,直连
  - DOMAIN-SUFFIX,1.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.0.ip6.arpa,直连
  - DOMAIN-SUFFIX,10.in-addr.arpa,直连
  - DOMAIN-SUFFIX,100.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,100.51.198.in-addr.arpa,直连
  - DOMAIN-SUFFIX,101.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,102.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,103.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,104.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,105.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,106.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,107.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,108.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,109.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,110.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,111.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,112.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,113.0.203.in-addr.arpa,直连
  - DOMAIN-SUFFIX,113.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,114.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,115.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,116.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,117.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,118.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,119.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,120.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,121.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,122.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,123.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,124.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,125.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,126.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,127.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,127.in-addr.arpa,直连
  - DOMAIN-SUFFIX,16.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,168.192.in-addr.arpa,直连
  - DOMAIN-SUFFIX,17.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,18.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,19.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,2.0.192.in-addr.arpa,直连
  - DOMAIN-SUFFIX,20.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,21.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,22.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,23.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,24.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,25.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,254.169.in-addr.arpa,直连
  - DOMAIN-SUFFIX,255.255.255.255.in-addr.arpa,直连
  - DOMAIN-SUFFIX,26.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,27.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,28.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,29.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,30.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,31.172.in-addr.arpa,直连
  - DOMAIN-SUFFIX,64.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,65.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,66.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,67.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,68.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,69.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,70.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,71.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,72.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,73.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,74.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,75.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,76.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,77.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,78.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,79.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,8.b.d.0.1.0.0.2.ip6.arpa,直连
  - DOMAIN-SUFFIX,8.e.f.ip6.arpa,直连
  - DOMAIN-SUFFIX,80.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,81.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,82.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,83.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,84.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,85.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,86.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,87.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,88.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,89.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,9.e.f.ip6.arpa,直连
  - DOMAIN-SUFFIX,90.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,91.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,92.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,93.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,94.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,95.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,96.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,97.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,98.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,99.100.in-addr.arpa,直连
  - DOMAIN-SUFFIX,a.e.f.ip6.arpa,直连
  - DOMAIN-SUFFIX,acl4.ssr,直连
  - DOMAIN-SUFFIX,b.e.f.ip6.arpa,直连
  - DOMAIN-SUFFIX,captive.apple.com,直连
  - DOMAIN-SUFFIX,connectivitycheck.gstatic.com,直连
  - DOMAIN-SUFFIX,d.f.ip6.arpa,直连
  - DOMAIN-SUFFIX,hiwifi.com,直连
  - DOMAIN-SUFFIX,home.arpa,直连
  - DOMAIN-SUFFIX,leike.cc,直连
  - DOMAIN-SUFFIX,localhost.ptlogin2.qq.com,直连
  - DOMAIN-SUFFIX,localhost.sec.qq.com,直连
  - DOMAIN-SUFFIX,location.services.mozilla.com,直连
  - DOMAIN-SUFFIX,msftconnecttest.com,直连
  - DOMAIN-SUFFIX,msftncsi.com,直连
  - DOMAIN-SUFFIX,my.router,直连
  - DOMAIN-SUFFIX,networkcheck.kde.org,直连
  - DOMAIN-SUFFIX,p.to,直连
  - DOMAIN-SUFFIX,peiluyou.com,直连
  - DOMAIN-SUFFIX,phicomm.me,直连
  - DOMAIN-SUFFIX,plex.direct,直连
  - DOMAIN-SUFFIX,router.ctc,直连
  - DOMAIN-SUFFIX,routerlogin.com,直连
  - DOMAIN-SUFFIX,tendawifi.com,直连
  - DOMAIN-SUFFIX,test.steampowered.com,直连
  - DOMAIN-SUFFIX,tplinkwifi.net,直连
  - DOMAIN-SUFFIX,tplogin.cn,直连
  - DOMAIN-SUFFIX,ts.net,直连
  - DOMAIN-SUFFIX,wifi.cmcc,直连
  - DOMAIN-SUFFIX,zte.home,直连
  - IP-CIDR,0.0.0.0/8,直连,no-resolve
  - IP-CIDR,10.0.0.0/8,直连,no-resolve
  - IP-CIDR,100.64.0.0/10,直连,no-resolve
  - IP-CIDR,127.0.0.0/8,直连,no-resolve
  - IP-CIDR,169.254.0.0/16,直连,no-resolve
  - IP-CIDR,172.16.0.0/12,直连,no-resolve
  - IP-CIDR,192.0.0.0/24,直连,no-resolve
  - IP-CIDR,192.0.2.0/24,直连,no-resolve
  - IP-CIDR,192.168.0.0/16,直连,no-resolve
  - IP-CIDR,192.88.99.0/24,直连,no-resolve
  - IP-CIDR,198.18.0.0/15,直连,no-resolve
  - IP-CIDR,198.51.100.0/24,直连,no-resolve
  - IP-CIDR,203.0.113.0/24,直连,no-resolve
  - IP-CIDR,224.0.0.0/3,直连,no-resolve
  - IP-CIDR6,::/127,直连,no-resolve
  - IP-CIDR6,fc00::/7,直连,no-resolve
  - IP-CIDR6,fe80::/10,直连,no-resolve
  - IP-CIDR6,ff00::/8,直连,no-resolve
  - GEOIP,LAN,直连
  - GEOIP,CN,直连
# 长风网站，自动注入
  - DOMAIN-SUFFIX,v2rayse.com,节点选择
  - DOMAIN-SUFFIX,cff.pw,节点选择
  - DOMAIN-SUFFIX,vpnse.org,节点选择
  - DOMAIN-SUFFIX,cfmem.com,节点选择
  - MATCH,节点选择
